#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/scripts/common.sh"

RUNTIME_DIR="$SCRIPT_DIR/.runtime"
FONT_DIR="$RUNTIME_DIR/fonts"
CACHE_DIR="$RUNTIME_DIR/cache"
OPAM_SWITCH="4.14.0"

FONT_NAME="PxPlus_IBM_VGA8.ttf"
FONT_PATH="$FONT_DIR/$FONT_NAME"
FONT_URL="https://raw.githubusercontent.com/pocketfood/Fontpkg-PxPlus_IBM_VGA8/master/PxPlus_IBM_VGA8.ttf"

OS_TYPE="$(uname -s)"
echo "Targeting OS: $OS_TYPE"

export OPAMYES=true

mkdir -p "$FONT_DIR" "$CACHE_DIR"

# Node.js must be installed before running bootstrap (via nvm, fnm, Homebrew, or system package).
# We intentionally do not install it here to avoid trampling version managers.
if ! command -v node &>/dev/null; then
  echo "ERROR: node is not in PATH." >&2
  echo "Install Node.js 18+ via nvm (https://github.com/nvm-sh/nvm), fnm, or your system package manager." >&2
  exit 1
fi
echo "node $(node --version) found at $(command -v node)"

case "$OS_TYPE" in
  Darwin*)
    echo "Installing via OPAM (recommended for macOS)..."

    brew install opam pkg-config ffmpeg yt-dlp

    if [[ ! -d "$HOME/.opam" ]]; then
      opam init --bare -y
    fi

    if ! opam switch list --short | grep -Fxq "4.14.0"; then
      echo "Creating OPAM switch 4.14.0..."
      opam switch create 4.14.0 --package=ocaml-base-compiler.4.14.0 -y
    else
      echo "OPAM switch 4.14.0 already exists."
    fi

    eval "$(opam env --switch=$OPAM_SWITCH)"

    # Install Liquidsoap and related packages directly.
    # No depext: it is not needed here and is breaking on newer opam.
    opam install -y liquidsoap ffmpeg ssl cry sdl-liquidsoap
    ;;

  Linux*)
    echo "Installing Linux dependencies and OPAM toolchain..."
    if ! command -v apt-get &>/dev/null; then
      echo "ERROR: apt-get not found. Only Debian/Ubuntu are supported by this bootstrap." >&2
      echo "On other distros, install the equivalent packages manually (see README)." >&2
      exit 1
    fi
    sudo apt-get update
    sudo apt-get install -y \
      build-essential \
      opam \
      pkg-config \
      m4 \
      yt-dlp \
      ffmpeg \
      curl \
      xvfb \
      netcat-openbsd \
      bubblewrap \
      libgmp-dev \
      libpcre2-dev \
      libssl-dev \
      libsamplerate0-dev \
      libtag1-dev \
      libyaml-dev \
      libao-dev \
      libavcodec-dev \
      libavdevice-dev \
      libavfilter-dev \
      libavformat-dev \
      libavutil-dev \
      libswresample-dev \
      libswscale-dev \
      libsdl2-dev \
      libsdl2-ttf-dev \
      libsdl2-image-dev

    if [[ ! -d "$HOME/.opam" ]]; then
      opam init --bare -y --disable-sandboxing
    fi

    if ! opam switch list --short | grep -Fxq "$OPAM_SWITCH"; then
      echo "Creating OPAM switch $OPAM_SWITCH..."
      opam switch create "$OPAM_SWITCH" --package=ocaml-base-compiler.4.14.0 -y
    else
      echo "OPAM switch $OPAM_SWITCH already exists."
    fi

    eval "$(opam env --switch=$OPAM_SWITCH)"

    opam install -y liquidsoap ffmpeg ssl cry sdl-liquidsoap

    # chromium-browser was dropped from apt on Ubuntu 22.04+ (snap only).
    # Try the Debian package name first; fall back silently — detect_chrome_bin handles runtime lookup.
    if ! command -v chromium &>/dev/null && ! command -v chromium-browser &>/dev/null; then
      sudo apt-get install -y chromium 2>/dev/null || sudo apt-get install -y chromium-browser 2>/dev/null || \
        echo "WARNING: Could not install Chromium via apt. Install it manually or set OVERLAY_BROWSER_PATH."
    fi
    ;;

  *)
    echo "Unsupported OS: $OS_TYPE" >&2
    exit 1
    ;;
esac

if [[ ! -f "$FONT_PATH" ]]; then
  echo "Downloading IBM VGA font to $FONT_PATH ..."
  curl -L "$FONT_URL" -o "$FONT_PATH"
else
  echo "Font already present at $FONT_PATH"
fi

# Install MediaMTX
if ! command -v mediamtx &>/dev/null; then
  echo "Installing MediaMTX..."
  VERSION="v1.12.3" # Check their GitHub for the latest if you need newer
  wget -qO- "https://github.com/bluenviron/mediamtx/releases/download/$VERSION/mediamtx_${VERSION}_linux_amd64.tar.gz" | tar -xz -C /usr/local/bin mediamtx
  chmod +x /usr/local/bin/mediamtx
else
  echo "MediaMTX already installed."
fi

CHROME_BIN=""
if detected="$(detect_chrome_bin 2>/dev/null)"; then
  CHROME_BIN="$detected"
fi

cat > "$SCRIPT_DIR/.env.runtime" <<EOF
# Generated by bootstrap.sh
OVERLAY_FONT=$FONT_PATH
RUNTIME_DIR=$RUNTIME_DIR
OVERLAY_HOST=127.0.0.1
OVERLAY_PORT=8050
OVERLAY_FEED_URL=udp://127.0.0.1:8051
OPAM_SWITCH=$OPAM_SWITCH
OVERLAY_BROWSER_PATH=$CHROME_BIN
EOF

echo "------------------------------------------------"
echo "Bootstrap complete."

echo "Runtime dir: $RUNTIME_DIR"
echo "Font path:   $FONT_PATH"
echo "Wrote:       $SCRIPT_DIR/.env.runtime"

if command -v opam &>/dev/null; then
  echo "Run: eval \$(opam env --switch=$OPAM_SWITCH)"
fi
